sdf

diff --git a/Jenkinsfiled b/Jenkinsfiled
--- a/Jenkinsfiled
+++ b/Jenkinsfiled
@@ -11,7 +11,8 @@ pipeline {
     stages {
         stage ("one") {
             steps {
-                echo tage one
+                echo "stage one"
+                exit 1
             }
         }
         stage ("two") {
@@ -25,7 +26,7 @@ pipeline {
             echo " i say hello always"
         }
         failure {
-            echo " you failed , you should try again"
+            echo "  you failed , you should try again"
         }
     }
 }
